server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://replica1:8761/eureka/