server:
  port: 8866
spring:
  application:
    name: sleuth
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://replica1:8761/eureka/,http://replica2:8762/eureka/