server:
  port: 8893
spring:
  application:
    name: module-3
  zipkin:
    base-url: http://localhost:8866/
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://replica1:8761/eureka/,http://replica2:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,health,info