server:
  port: 8866

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sleuth

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://replica1:8761/eureka/,http://replica2:8762/eureka/